### ISSUE TITLE
使用 /edit 修改内容提交后，Bot 卡死

### ISSUE THREAD

**Issue by ShadowsSide** [chr233/XinjingdailyBot#15]
I 2023/08/01 18:45:19.130 [XinjingdailyBot.Service.Bot.Common.UpdateService] 【私聊|CyrusAntony】 Cyrus Antony(@AntonyCyrus) [文本] /start 
E 2023/08/01 18:45:19.142 [XinjingdailyBot.Service.Bot.Common.PollingService] 接收服务运行出错 MySqlConnector.MySqlException (0x80004005): Duplicate entry '5767935565-7773' for key 'dialogue.index_chat'
   at SqlSugar.MySqlProvider.ExecuteCommandAsync(String sql, SugarParameter[] parameters)
   at SqlSugar.MySqlProvider.ExecuteCommandAsync(String sql, SugarParameter[] parameters)
   at SqlSugar.InsertableProvider`1.ExecuteCommandAsync()
   at SqlSugar.SimpleClient`1.InsertAsync(T insertObj)
   at XinjingdailyBot.Service.Data.DialogueService.RecordMessage(Message message)
   at XinjingdailyBot.Service.Bot.Common.DispatcherService.OnMessageReceived(Users dbUser, Message message)
   at XinjingdailyBot.Service.Bot.Common.UpdateService.HandleUpdateAsync(ITelegramBotClient _, Update update, CancellationToken cancellationToken)
   at Telegram.Bot.Polling.DefaultUpdateHandler.HandleUpdateAsync(ITelegramBotClient botClient, Update update, CancellationToken cancellationToken)
   at Telegram.Bot.Polling.DefaultUpdateReceiver.ReceiveAsync(IUpdateHandler updateHandler, CancellationToken cancellationToken)
   at Telegram.Bot.TelegramBotClientExtensions.ReceiveAsync(ITelegramBotClient botClient, IUpdateHandler updateHandler, ReceiverOptions receiverOptions, CancellationToken cancellationToken)
   at Telegram.Bot.TelegramBotClientExtensions.ReceiveAsync(ITelegramBotClient botClient, Func`4 updateHandler, Func`4 pollingErrorHandler, ReceiverOptions receiverOptions, CancellationToken cancellationToken)
   at XinjingdailyBot.Service.Bot.Common.PollingService.DoWork(CancellationToken stoppingToken) Server Error Code: 1062;SqlState: 23000

**Comment by zhong820290** [comment]
> 打开配置文件中的 ThrowPendingUpdates 选项可以缓解这个问题

**Comment by zhong820290** [comment]
> 打开配置文件中的 ThrowPendingUpdates 选项可以缓解这个问题

我今天也遇到此类的情况,请问打开 ThrowPendingUpdates 选项,还会出现这个错误吗?有望下次更新可以解决?

**Comment by chr233** [comment]
> > 打开配置文件中的 ThrowPendingUpdates 选项可以缓解这个问题
> 
> 我今天也遇到此类的情况,请问打开 ThrowPendingUpdates 选项,还会出现这个错误吗?有望下次更新可以解决?

看了下代码，有这方面的设定，但是不知道为什么原因，ThrowPendingUpdates 禁用的时候这部分不生效，而 ThrowPendingUpdates 打开的时候这部分代码也没有意义了，感觉应该是一个bug

**Comment by chr233** [comment]
已更新

**Comment by ShadowsSide** [comment]
> 已更新

尝试使用最新版本后，尝试编辑了一两条，暂未复现异常。感谢开发者~
